project:
  type: website
  output-dir: docs

website:
  title: "Paityn Richardson"
  navbar:
    left: 
      - text: "Summer 2025"
        menu:
          - href: ResearchPoster.qmd
          - text: "Research Blog"
            href: ResearchBlog.qmd
      - text: "Projects"
        menu:
          - text: "WNBA Ranking Analysis"
            href: WNBA_RankAnalysis.qmd
      - text: "Data Viz"
        menu: 
          - text: "Rodent Species"
            href: Rodentdata.qmd
          - text: "Coffee Ratings"
            href: CoffeeRatings.qmd
          - text: "Spotify Patterns"
            href: FinalProject2.qmd
          - text: "Poker Hand Probability"
            href: Project3.qmd
          - text: "WAI Database Study"
            href: WAIDatabaseStudy.qmd
          - text: "Simulated Spotify Wrapped"
            href: SimulatedSpotify.qmd
          

format:
  html:
    theme: sketchy
    css: styles.css

editor: visual
